#Here change the value for Gamerule's condition.
gameruleCondition: "&7Gamerule is currently set to: "
#Here change the default value message.
gameruleDefaultValue: "&7Default value is: "
#Reset Gamerules lore
resetGamerule: "&7Reset all Gamerules to default values."
#Copy Gamerules lore
copyGamerule: "&7Copy all gamerules values from world "
#Paste Gamerules lore
pasteGamerule: "&7Paste all gamerules values from the world you copied."
#Check the list with minecraft gamerules here: https://minecraft.fandom.com/wiki/Game_rule#List_of_game_rules
announceAdvancements: "&7Whether advancements should be announced in chat."
blockExplosionDropDecay: "&7Whether block loot is dropped by all blocks (false) or randomly (true)."
commandBlockOutput: "&7Whether command blocks should notify admins when they perform commands."
disableElytraMovementCheck: "&7Whether the server should skip checking player speed when the player is wearing elytra."
disableRaids: "&7Whether raids are disabled."
doDaylightCycle: "&7Whether the daylight cycle and moon phases progress."
doEntityDrops: "&7Whether entities that are not mobs should have drops."
doFireTick: "&7Whether fire should spread and naturally extinguish."
doInsomnia: "&7Whether phantoms can spawn in the nighttime."
doImmediateRespawn: "&7Players respawn immediately without showing the death screen."
doLimitedCrafting: "&7Whether players should be able to craft only those recipes that they've unlocked first."
doMobLoot: "&7Whether mobs should drop items and experience orbs."
doMobSpawning: "&7Whether mobs should naturally spawn. Does not affect monster spawners."
doPatrolSpawning: "&7Whether patrols can spawn."
doTileDrops: "&7Whether blocks should have drops."
doTraderSpawning: "&7Whether wandering traders can spawn."
doWardenSpawning: "&7Whether wardens can spawn."
doWeatherCycle: "&7Whether the weather can change naturally."
drowningDamage: "&7Whether the player should take damage when drowning."
fallDamage: "&7Whether the player should take fall damage."
fireDamage: "&7Whether the player should take damage in fire, lava, campfires, or on magma blocks."
forgiveDeadPlayers: "&7Makes angered neutral mobs stop being angry when the targeted player dies nearby."
freezeDamage: "&7Whether the player should take damage when inside powder snow."
globalSoundEvents: "&7Whether certain sound events are heard by all players regardless of location."
keepInventory: "&7Whether the player should keep items and experience in their inventory after death."
lavaSourceConversion: "&7Whether new sources of lava are allowed to form."
logAdminCommands: "&7Whether to log admin commands to server log."
maxCommandChainLength: "&7The maximum length of a chain of commands that can be executed during one tick."
maxEntityCramming: "&7The maximum number of pushable entities a player can push before taking 3 suffocation damage."
mobExplosionDropDecay: "&7Whether block loot is dropped by all blocks (false) or randomly (true)."
mobGriefing: "&7Whether mobs can pick up items and be able to change blocks."
naturalRegeneration: "&7Whether the player can regenerate health naturally if their hunger is full enough."
playersSleepingPercentage: "&7What percentage of players must sleep to skip the night."
randomTickSpeed: "&7How often a random block tick occurs such as plant growth per chunk section per game tick."
reducedDebugInfo: "&7Whether the debug screen shows all or reduced information."
sendCommandFeedback: "&7Whether the feedback from commands executed by a player should show up in chat."
showDeathMessages: "&7Whether death messages are put into chat when a player dies."
snowAccumulationHeight: "&7The maximum number of snow layers that can be accumulated on each block."
spawnRadius: "&7The number of blocks from the world spawn that a player spawns in when first joining a server."
spectatorsGenerateChunks: "&7Whether players in spectator mode can generate chunks."
tntExplosionDropDecay: "&7Whether block loot is dropped by all blocks (false) or randomly (true)."
universalAnger: "&7Makes angered neutral mobs attack any nearby player."
waterSourceConversion: "&7Whether new sources of water are allowed to form."