#Here change the value for Gamerule's condition.
gameruleCondition: "&7Gamerule is currently set to: "
#Here change the default value message.
gameruleDefaultValue: "&7Default value is: "
#Reset Gamerules lore
resetGamerule: "&7Reset all Gamerules to default values."
#Copy Gamerules lore
copyGamerule: "&7Copy all gamerules values from world "
#Paste Gamerules lore
pasteGamerule: "&7Paste all gamerules values from the world you copied."
#Check the list with minecraft gamerules here: https://minecraft.fandom.com/wiki/Game_rule#List_of_game_rules
#You can use the '\n' for a new line but you have to color the text again.
announceAdvancements: "&7Whether advancements \n&7should be announced in chat."
blockExplosionDropDecay: "&7Whether block loot is \n&7dropped by all blocks (false) or randomly (true)."
commandBlockOutput: "&7Whether command blocks should \n&7 notify admins when they perform commands."
commandModificationBlockLimit: "&7Controls the maximum number of blocks \n&7changed when using /clone, /fill, or /fillbiome."
disableElytraMovementCheck: "&7Whether the server should skip checking \n&7player speed when the player is wearing elytra."
disableRaids: "&7Whether raids are disabled."
doDaylightCycle: "&7Whether the daylight cycle \n&7and moon phases progress."
doEntityDrops: "&7Whether entities that are \n&7not mobs should have drops."
doFireTick: "&7Whether fire should spread \n&7and naturally extinguish."
doInsomnia: "&7Whether phantoms can \n&7spawn in the nighttime."
doImmediateRespawn: "&7Players respawn immediately \n&7without showing the death screen."
doLimitedCrafting: "&7Whether players should be able\n&7 to craft only those recipes that \n&7they've unlocked first."
doMobLoot: "&7Whether mobs should drop items \n&7and experience orbs."
doMobSpawning: "&7Whether mobs should naturally spawn.\n&7Does not affect monster spawners."
doPatrolSpawning: "&7Whether patrols can spawn."
doTileDrops: "&7Whether blocks should have drops."
doTraderSpawning: "&7Whether wandering traders can spawn."
doVinesSpread: "&7Whether vines can spread to other blocks.\n&7Cave vines, weeping vines, \n&7and twisting vines are not affected."
doWardenSpawning: "&7Whether wardens can spawn."
doWeatherCycle: "&7Whether the weather can change naturally."
drowningDamage: "&7Whether the player should \n&7take damage when drowning."
fallDamage: "&7Whether the player should take fall damage."
fireDamage: "&7Whether the player should take \n&7damage in fire, lava, campfires,\n&7or on magma blocks."
forgiveDeadPlayers: "&7Makes angered neutral mobs \n&7stop being angry when the \n&7targeted player dies nearby."
freezeDamage: "&7Whether the player should take \n&7damage when inside powder snow."
globalSoundEvents: "&7Whether certain sound events \n&7are heard by all players \n&7regardless of location."
keepInventory: "&7Whether the player should keep items \n&7and experience in their inventory after death."
lavaSourceConversion: "&7Whether new sources of lava are allowed to form."
logAdminCommands: "&7Whether to log admin commands to server log."
maxCommandChainLength: "&7The maximum length of a chain of commands \n&7that can be executed during one tick."
maxEntityCramming: "&7The maximum number of pushable entities \n&7a player can push before \n&7taking 3 suffocation damage."
mobExplosionDropDecay: "&7Whether block loot is dropped by \n&7all blocks (false) or randomly (true)."
mobGriefing: "&7Whether mobs can pick up items \n&7and be able to change blocks."
naturalRegeneration: "&7Whether the player can regenerate health \n&7naturally if their hunger is full enough."
playersSleepingPercentage: "&7What percentage of players must \n&7sleep to skip the night."
randomTickSpeed: "&7How often a random block tick \n&7occurs such as plant growth \n&7per chunk section per game tick."
reducedDebugInfo: "&7Whether the debug screen shows \n&7all or reduced information."
sendCommandFeedback: "&7Whether the feedback from commands \n&7executed by a player should show up in chat."
showDeathMessages: "&7Whether death messages are put \n&7into chat when a player dies."
snowAccumulationHeight: "&7The maximum number of snow layers \n&7that can be accumulated on each block."
spawnRadius: "&7The number of blocks from the world spawn \n&7that a player spawns in \n&7when first joining a server."
spectatorsGenerateChunks: "&7Whether players in spectator mode\n&7can generate chunks."
tntExplosionDropDecay: "&7Whether block loot is dropped \n&7by all blocks (false) or randomly (true)."
universalAnger: "&7Makes angered neutral mobs attack any nearby player."
waterSourceConversion: "&7Whether new sources of water are allowed to form."