name: GamerulesManager
version: '${project.version}'
main: me.ted2001.gamerulesmanager.GamerulesManager
api-version: 1.13
authors: [ Ted_2001 ]
description: Configurate world's gamerules via gui.
commands:
  gamerule:
    description: Open GUI Manager.
    permission: gamerulemanager.use
    aliases: [mgamerule,ggamerule,gamerules,gamerulemanager]